Repository gacela-project/container, pull requests merged in 2023-04, with the labels that each got.

#2 Add static instance create
  src/Resolver/InstanceCreator.php
  tests/Unit/InstanceCreatorTest.php
Labels: enhancement

#5 Implement PSR-11 on InsanceCreator class
  composer.json
  src/Resolver/Container.php
  src/Resolver/Exception/DependencyInvalidArgumentException.php
  src/Resolver/Exception/DependencyNotFoundException.php
  tests/Unit/ContainerTest.php
Labels: enhancement

#7 Update readme
  CHANGELOG.md
  README.md
Labels: documentation

#8 Resolve classes
  CHANGELOG.md
  src/Resolver/Container.php
  tests/Unit/ContainerTest.php
Labels: bug, enhancement

#10 Allow set instance by id
  src/Container/Container.php
  src/Container/ContainerInterface.php
  src/Container/Exception/ContainerException.php
  tests/Unit/ContainerTest.php
Labels: enhancement
